sonar.projectKey=bingeboxed
sonar.projectName=BingeBoxed
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=sqp_8851c467f190ca3bc013f0401f5aa603bcf9ef29